---
abstract: 'Most commonly needed test functions and features.'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Most
provides:
  Test::Most:
    file: lib/Test/Most.pm
    version: 0.24
  Test::Most::Exception:
    file: lib/Test/Most/Exception.pm
    version: 0.24
recommends:
  Data::Dumper::Names: 0.03
requires:
  Carp::Always: 0.10
  Exception::Class: 1.14
  Test::Deep: 0.106
  Test::Differences: 0.61
  Test::Exception: 0.31
  Test::Harness: 3.21
  Test::More: 0.88
  Test::Warn: 0.23
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Ovid/test--most
version: 0.24
